accounts/urls.py
# from django.contrib import admin
from django.urls import path


from . import views


app_name = 'accounts'


urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('signup/done', views.SignUpDoneView.as_view(), name='signup_done'),
    path('signup/complete/<token>', views.SignUpCompleteView.as_view(), name='signup_complete'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('settings/<uuid:pk>', views.ChangeSettingsView.as_view(), name='settings'),
    path('profile/<uuid:pk>', views.ProfileUpdateView.as_view(), name='profile_settings'),
]

apis/urls.py
""" Rest framework API URL settings """
from django.urls import path, include
from rest_framework import routers


from .views import PostAPIView, PostEvalAPIView, PostHitAPIView, CommentAPIView


router = routers.DefaultRouter()

router.register(r'posts', PostAPIView)
router.register(r'post_evals', PostEvalAPIView)
router.register(r'post_hits', PostHitAPIView)
router.register(r'comments', CommentAPIView)


app_name = 'apis'
urlpatterns = [
    path(r'', include(router.urls))
]


"""
Url pattern name is the lower case of queryset object in the viewset

The example of url patterns
    View: queryset=User.objects.all()
        URL pattern: ^users/$ , Name: 'user-list'
        URL pattern: ^users/{pk}/$ , Name: 'user-detail'

When referencing ^users/{pk}, write {% url 'apis:user-detail' user.pk %} in your templates

"""

blogs/urls.py
# from django.contrib import admin
from django.urls import path


from . import views


app_name = 'blogs'


urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('about/<uuid:pk>', views.PostDetailView.as_view(), name='detail'),
    path('post/', views.PostCreateView.as_view(), name='post'),
    path('edit/<uuid:pk>', views.PostUpdateView.as_view(), name='edit'),
    path('delete/<uuid:pk>', views.PostDeleteView.as_view(), name='delete'),
    path('result/', views.SearchResultPostView.as_view(), name='result'),
    # path('result/filter', views.SearchFilterView.as_view(), name='search_filter'),
    path('user/<uuid:pk>/home', views.UserPageView.as_view(), name='user_page'),
    path('user/<uuid:pk>/posts', views.UserPostListView.as_view(), name='user_posts'),
    path('user/<uuid:pk>/profile', views.UserProfileView.as_view(), name='user_profile'),
]

myblogapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('apis.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
""" Account model """
from uuid import uuid4
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.core.mail import send_mail
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.contrib.auth.validators import UnicodeUsernameValidator
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill


# Default user icon image ( /media/DEFAULT_USER_ICON_IMAGE )
DEFAULT_USER_ICON_IMAGE = 'default-user-icon.png'

# Create your models here.
class UserManager(BaseUserManager):
    """ User manager """
    use_in_migrations = True

    def _create_user(self, username, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email must be set.')
        email = self.normalize_email(email)
        username = self.model.normalize_username(username)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, email, password, **extra_fields)

    def create_superuser(self, username, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(username, email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """ User model """
    username_validator = UnicodeUsernameValidator()

    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)

    username = models.CharField(
        _('username'),
        max_length=20,
        validators=[username_validator],
    )
    email = models.EmailField(
        _('email address'),
        max_length=100,
        unique=True,
        error_messages={
            'unique': _('This email address is already registered in other account')
        }
    )

    icon_image = ProcessedImageField(
        upload_to=settings.USER_ICON_UPLOAD_DIR,
        processors=[ResizeToFill(200, 200)],
        format='JPEG',
        options={'quality': 60},
        default=DEFAULT_USER_ICON_IMAGE
    )

    profile_message = models.TextField(
        max_length=500,
        blank=True,
    )

    first_name = models.CharField(_('first name'), max_length=20, blank=True)
    last_name = models.CharField(_('last name'), max_length=20, blank=True)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
    )

    birth_date = models.DateField(_('birth_date'), default=timezone.now)
    reg_date = models.DateTimeField(_('registration date'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user"""
        send_mail(subject, message, from_email, [self.email], **kwargs)

accounts/forms.py
""" Account form """
from django.contrib.auth.forms import (
    UserCreationForm, UsernameField, UserChangeForm, AuthenticationForm)
from django.forms.models import ModelForm
from django.forms import (
    CharField, EmailField, TextInput, EmailInput, PasswordInput)


from .models import User


class UserCreateForm(UserCreationForm):
    """ User creatino form """
    password1 = CharField(max_length=50, min_length=6, widget=PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email')
        field_classes = {
            'username': UsernameField,
            'email': EmailField
        }
        widgets = {
            'username': TextInput(attrs={'id': 'id_username'}),
            'email': EmailInput(attrs={'id': 'id_email'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        del self.fields['password2']
        self.fields['password1'].label = 'Password'
        self.fields['password1'].help_text = 'Make sure it\'s at least 6 characters.'

    def clean_email(self):
        email = self.cleaned_data['email']
        return email


class LoginForm(AuthenticationForm):
    """ Login form """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def non_field_errors(self):
        error_messages = super().non_field_errors()
        if error_messages:
            error_messages[0] = 'Incorrect Email address or Password'
        return error_messages


class CustomUserChangeForm(UserChangeForm):
    """ User settings change form """
    password = None

    class Meta:
        model = User
        fields = ('username', 'email')
        field_classes = {
            'username': UsernameField,
            'email': EmailField
        }
        widgets = {
            'username': TextInput(attrs={'id': 'id_username'}),
            'email': EmailInput(attrs={'id': 'id_email'}),
        }


class ProfileForm(ModelForm):
    """ Profile settings form """
    class Meta:
        model = User
        fields = ('icon_image', 'birth_date')

accounts/views.py
""" Account views """
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.http import HttpResponseBadRequest
from django.views import generic
from django.core.signing import dumps, loads, SignatureExpired, BadSignature
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string


from .forms import UserCreateForm, LoginForm, CustomUserChangeForm, ProfileForm


User = get_user_model()


# Create your views here.
class SignUpView(generic.CreateView):
    """
    User creation view\n
    Send authentication email to registered email address

    User's is_active param is still False here
    """
    # WARNING: Set email settings in settings.py
    form_class = UserCreateForm
    template_name = 'accounts/signup.html'

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': self.request.scheme,
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }

        subject = render_to_string('accounts/mail_templates/signup/subject.txt', context)
        message = render_to_string('accounts/mail_templates/signup/message.txt', context)

        user.email_user(subject, message)
        return redirect('accounts:signup_done')


class SignUpDoneView(generic.TemplateView):
    """ Sign up done view"""
    template_name = 'accounts/signup_done.html'


class SignUpCompleteView(generic.TemplateView):
    """
    Sign up complete view\n
    User should click authentication url in sended email text

    User's is_active param become True
    """
    template_name = 'accounts/signup_complete.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)

    def get(self, request, **kwargs):
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)

        except SignatureExpired:
            return HttpResponseBadRequest()

        except BadSignature:
            return HttpResponseBadRequest()

        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoesNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    user.is_active = True
                    user.save()
                    return super().get(request, **kwargs)

        return HttpResponseBadRequest()


class Login(LoginView):
    """ Login view"""
    form_class = LoginForm
    template_name = 'accounts/login.html'


class Logout(LoginRequiredMixin, LogoutView):
    """Logout view"""
    pass


class ChangeSettingsView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    """ Change user settings view"""
    login_url = reverse_lazy('accounts:login')
    model = User
    form_class = CustomUserChangeForm
    template_name = 'accounts/settings.html'

    def test_func(self):
        current_user = self.request.user
        page_user = get_object_or_404(self.model, pk=self.kwargs['pk'])
        return current_user.pk == page_user.pk or current_user.is_superuser

    def get_success_url(self):
        return reverse_lazy('blogs:user_page', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        messages.success(self.request, 'saved successfully!')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, 'not saved - alert!')
        return super().form_invalid(form)


class ProfileUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    """ Change user profile view """
    login_url = reverse_lazy('accounts:login')
    model = User
    form_class = ProfileForm
    template_name = 'accounts/profile_settings.html'

    def test_func(self):
        current_user = self.request.user
        page_user = get_object_or_404(self.model, pk=self.kwargs['pk'])
        return current_user.pk == page_user.pk or current_user.is_superuser

    def get_success_url(self):
        return reverse_lazy('blogs:user_page', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        messages.success(self.request, 'saved successfully!')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, 'not saved - alert!')
        return super().form_invalid(form)

accounts/templates/accounts/logged_out.html
{% extends 'blogs/base.html' %}

{% block content %}

    <!-- <h1>Here is logged out </h1> -->

    <div class="container">

    </div>
    
    <a href="{% url 'blogs:index' %}"><button class="btn btn-primary"> TOP</button> </a>
    

{% endblock%}

accounts/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'blogs/css/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'blogs/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/style.css' %}">
    <!-- jQuery -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="{% static 'blogs/js/js/jquery.bottom-1.0.js' %}"></script>
</head>

<body>
    <!-- <h1>Here is Login form </h1> -->

    <div class="text-center my-5">
        <a href="{% url 'blogs:index' %}" id="top">
            <span>
                TOP
            </span>

        </a>
    </div>

    <div class="container">
            {% if form.non_field_errors %}
            <div id="non-field-errors" class="alert alert-danger alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ form.non_field_errors }}
            </div>
            {% endif %}
    

        <div id="login-form-container">
            <form method="post">
                {% csrf_token %}
                {% for field in form %}
                <div class="row justify-content-center">
                    <div class="field col-12 mt-4 text-center">
                        {{ field.label }}
                    </div>
                    <div class="field col-12 mt-3 text-center">
                        {{ field }}
                    </div>
                </div>
                {% endfor %}

                <div class="row">
                    <div class="col-10 mt-5 mx-auto">
                        <button type="submit" class="btn btn-primary btn-lg w-100">
                            <div>
                                Sign in
                            </div>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!-- Bootstrap4 -->
    <script src="{% static 'blogs/js/js/bootstrap.bundle.min.js' %}"></script>
</body>

</html>

accounts/templates/accounts/profile_settings.html
{% extends 'blogs/base.html' %}

{% block content %}

<!-- <h1 class="headline">Here is Profile settings!!!</h1> -->



{% endblock%}

accounts/templates/accounts/settings.html
{% extends 'blogs/base.html' %}

{% block content %}

    <!-- <h1> Here is setting form {{ user.username }} </h1> -->

    <div class="container my-5">
            <form method="post">
                {% csrf_token %}
                {{ form.non_field_errors }}
                {% for field in form %}
                <div class="row">      
                    <div class="field col-12 mt-3 text-center">
                        {{ field.label }}
                    </div>
                    <div class="field col-12 my-4 text-center">
                        {{ field }}
                    </div>
                    <div class="field col-12">
                        {% if field.help_text %}
                        <span class="field_help_text">{{ field.help_text}}</span>
                        {% endif %}
                    </div>
                    <div class="field col-12">
                        {{ field.errors }}
                    </div>
                </div>
                {% endfor %}

                <div class="row flex-column align-items-center">
                    <div class="col-2 col-sm-2 my-3 text-center"><button type="submit" class="btn btn-primary btn-lg">Confirm</button></div>
                </div>
            </form>

            <div>
                <a href="{% url 'password_change' %}">
                    <button class="btn">Password Change</button>
                </a>
            </div>
    </div>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'blogs/base.html' %}

{% block content %}

<!-- <h1> Here is Signup </h1> -->

<div class="container my-5">
    <div id="sign-up-form-container">
        <form method="post">
            {% csrf_token %}
            <div id="non-field-errors">
                {{ form.non_field_errors }}
            </div>
            {% for field in form %}
            <div class="row">
                <div class="field col-12 mt-4">
                    {{ field.label }}
                </div>
                <div class="field col-12 mt-3">
                    {{ field }}
                </div>
                <div class="field col-12">
                    <div class="field_help_text">{{ field.help_text }}</div>
                </div>
                <div class="field col-12 mt-1">
                    {% if field.errors %}
                    <div class="field_error_text alert alert-danger" role="alert">{{ field.errors }}</div>
                    {% endif %}
                </div>
            </div>
            {% endfor %}

            <div class="row">
                <div class="col-10 my-5"><button type="submit" class="btn btn-primary btn-lg w-50">Send</button></div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/signup_complete.html
{% extends 'blogs/base.html' %}

{% block content %}

    <div class="container">
        <p>
            Registration Successful!<br>
            You can login here with email address and password.><br>
            <a class="btn btn-primary btn-lg" href="{% url 'login' %}">ログイン</a>
        </p>
    </div>

{% endblock %}

accounts/templates/accounts/signup_done.html
{% extends 'blogs/base.html' %}

{% block content %}

    <div class="container">
        <p>
            Confirmination email is sended to your registered email address. Signing up has not finished yet. Check the email message and complete your account signing up.
        </p>
    </div>

{% endblock %}