accounts/urls.py
# from django.contrib import admin
from django.urls import path


from . import views


app_name = 'accounts'


urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('signup/done', views.SignUpDoneView.as_view(), name='signup_done'),
    path('signup/complete/<token>', views.SignUpCompleteView.as_view(), name='signup_complete'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('settings/<uuid:pk>', views.ChangeSettingsView.as_view(), name='settings'),
    path('profile/<uuid:pk>', views.ProfileUpdateView.as_view(), name='profile_settings'),
]

apis/urls.py
""" Rest framework API URL settings """
from django.urls import path, include
from rest_framework import routers


from .views import PostAPIView, PostEvalAPIView, PostHitAPIView, CommentAPIView


router = routers.DefaultRouter()

router.register(r'posts', PostAPIView)
router.register(r'post_evals', PostEvalAPIView)
router.register(r'post_hits', PostHitAPIView)
router.register(r'comments', CommentAPIView)


app_name = 'apis'
urlpatterns = [
    path(r'', include(router.urls))
]


"""
Url pattern name is the lower case of queryset object in the viewset

The example of url patterns
    View: queryset=User.objects.all()
        URL pattern: ^users/$ , Name: 'user-list'
        URL pattern: ^users/{pk}/$ , Name: 'user-detail'

When referencing ^users/{pk}, write {% url 'apis:user-detail' user.pk %} in your templates

"""

blogs/urls.py
# from django.contrib import admin
from django.urls import path


from . import views


app_name = 'blogs'


urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('about/<uuid:pk>', views.PostDetailView.as_view(), name='detail'),
    path('post/', views.PostCreateView.as_view(), name='post'),
    path('edit/<uuid:pk>', views.PostUpdateView.as_view(), name='edit'),
    path('delete/<uuid:pk>', views.PostDeleteView.as_view(), name='delete'),
    path('result/', views.SearchResultPostView.as_view(), name='result'),
    # path('result/filter', views.SearchFilterView.as_view(), name='search_filter'),
    path('user/<uuid:pk>/home', views.UserPageView.as_view(), name='user_page'),
    path('user/<uuid:pk>/posts', views.UserPostListView.as_view(), name='user_posts'),
    path('user/<uuid:pk>/profile', views.UserProfileView.as_view(), name='user_profile'),
]

myblogapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('apis.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
""" Main app(blogs) model """
import datetime
from uuid import uuid4
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.core.validators import URLValidator
from django.contrib.auth import get_user_model
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill


User = get_user_model()


# Create your models here.
class Post(models.Model):
    """ Post model """
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)

    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=200)
    text = models.TextField(null=True, max_length=2000)
    image = models.ImageField(upload_to=settings.POST_IMAGE_UPLOAD_DIR, verbose_name='post image')
    image_thumbnail = ImageSpecField(
        source='image', processors=[ResizeToFill(640, 360)], format='JPEG', options={'quality': 60})
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True, default=timezone.now)
    hits = models.PositiveIntegerField(blank=True, null=True, default=0)
    goods = models.PositiveIntegerField(blank=True, null=True, default=0)
    bads = models.PositiveIntegerField(blank=True, null=True, default=0)

    def __str__(self):
        return self.title

    def publish(self):
        """ Publish this post now """
        self.published_date = timezone.now()
        self.save()

    def create(self, author):
        """ Create post """
        self.author = author
        self.publish()

    def was_published_recently(self):
        """ Whether the post was published within 1 day """
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.published_date <= now
    was_published_recently.admin_order_field = 'published_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def change_image_name(self, name):
        """ Change the post image name """
        self.image.name = name

    def count_hits(self):
        self.hits = PostHit.objects.filter(post=self.pk).count()
        return self.hits

    def count_goods(self):
        self.goods = PostEval.objects.filter(post=self.pk, good=True, bad=False).count()
        return self.goods
    
    def count_bads(self):
        self.bads = PostEval.objects.filter(post=self.pk, good=False, bad=True).count()
        return self.bads


class PostEval(models.Model):
    """ Post evaluation (good or bad) """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    good = models.BooleanField(default=False)
    bad = models.BooleanField(default=False)

    created_date = models.DateTimeField(default=timezone.now)


class PostFavorite(models.Model):
    """ A model for bookmarking post """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    favorite = models.BooleanField(default=False)

    created_date = models.DateTimeField(default=timezone.now)


class UserFavorite(models.Model):
    """ A model for bookmarking user """
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='userfavorite_set')
    target = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_befavorited_set')

    favorite = models.BooleanField(default=False)

    created_date = models.DateTimeField(default=timezone.now)


class PostHit(models.Model):
    """ Post hit model """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    hit = models.BooleanField(default=False)

    created_date = models.DateTimeField(default=timezone.now)


class Comment(models.Model):
    """ Comment model """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    text = models.TextField(max_length=200)

    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(default=timezone.now)
    was_updated = models.BooleanField(default=False)


class CommentReply(models.Model):
    """ A reply for comment model"""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    target = models.ForeignKey(Comment, on_delete=models.CASCADE)

    text = models.TextField(max_length=200)

    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(default=timezone.now)
    was_updated = models.BooleanField(default=False)
    

blogs/forms.py
""" Main app(blogs) form """
from django import forms


from .models import Post, Comment
from .widgets import FileInputWithPreview


class PostForm(forms.ModelForm):
    """ Post form """

    class Meta:
        model = Post
        fields = ('title', 'text', 'image')
        widgets = {
            'title': forms.TextInput(attrs={'rows':1, 'cols': 50, 'id': 'title_form'}),
            'text': forms.Textarea(attrs={'rows': 10, 'cols': 80, 'max-rows': 50, 'id': 'text_form'}),
            'image': FileInputWithPreview,
        }

blogs/views.py
""" Main app(blogs) Views """
import re
import datetime
from urllib.parse import urlencode
from logging import getLogger, config
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.db.models import Q


from .models import Post, PostEval, PostHit, Comment
from .forms import PostForm
from .logging_config import _config


config.dictConfig(_config)
logger = getLogger('blogsLogger')

User = get_user_model()


# Create your views here.
class PostListView(generic.ListView):
    """ List view of the posts created in the past """
    template_name = 'blogs/index.html'
    context_object_name = 'latest_post_list'
    paginate_by = 24

    def get_queryset(self):
        """ Return a queryset of posts whose pub_date is before now."""
        queryset = Post.objects.filter(
            published_date__lte=timezone.now()
        ).order_by('-hits')
        if not queryset:
            messages.info(self.request, 'No post exists.')
        return queryset


class SearchResultPostView(generic.ListView):
    """ List view for rendering search results of the given query """
    template_name = 'blogs/result.html'
    context_object_name = 'result_post_list'
    paginate_by = 24

    def __init__(self):
        super().__init__()
        self.sort_key = '-hits'
        self.start_day = 1

    def get(self, request, *args, **kwargs):
        if not request.GET.get('q'):
            return redirect('blogs:index')

        return super().get(request, *args, **kwargs)


    def get_queryset(self):
        """ Return queryset filtered by the given parameters """
        if not self.request.GET.get('q'):
            return None
        
        """ Get queryset matching with search words """
        query_list = self.parse_search_params(self.request.GET['q'])
        query = Q()
        for word in query_list:
            query = (
                query
                | Q(author__username__icontains=word)
                | Q(title__icontains=word)
            )
        
        """ sort """
        if self.request.GET.get('sort'):
            self.sort_key = self.request.GET['sort']
        
        """"""" filter """""""""
        """ day """
        if self.request.GET.get('day'):
            self.start_day = int(self.request.GET['day'])
            start_datetime = timezone.now() - datetime.timedelta(days=self.start_day)
            query = query & Q(
                published_date__range=(start_datetime, timezone.now()))

        return Post.objects.filter(query).order_by(self.sort_key)

    def get_context_data(self, **kwargs):
        """
        Return the context including some paths. Each path's query does not including one param.
        """
        context = super().get_context_data(**kwargs)
        query_context = {}
        if self.request.GET.get('q'):
            query_context['q'] = self.request.GET['q']
        if self.request.GET.get('sort'):
            query_context['sort'] = self.request.GET['sort']
        if self.request.GET.get('day'):
            query_context['day'] = self.request.GET['day']

        base_path = reverse_lazy('blogs:result')
        result_url = '{}?{}'.format(base_path, urlencode(query_context))
        result_urls = {
            'sort_path': re.sub(r'&sort=.+(?=&)|&sort=.+$', '', result_url),
            'day_path': re.sub(r'&day=.+(?=&)|&day=.+$', '', result_url),
        }
        context.update(result_urls)
        return context

    def parse_search_params(self, words):
        """ Parse the given search words into a list of words """
        words = str(words)
        search_words = re.split(r'\s+', words)
        return search_words


class PostDetailView(generic.DetailView):
    """ Detail view of posts """
    model = Post
    template_name = 'blogs/detail.html'

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.get_object()
        
        """ Comment list """
        context['comment_list'] = Comment.objects.filter(
            post = post
        ).order_by('-updated_date')

        """ Post Hit """
        context['post_hit'] = post.count_hits()

        """ Post Eval """
        context['post_eval_good'] = post.count_goods()
        context['post_eval_bad'] = post.count_bads()

        if not self.request.user.is_authenticated:
            return context

        """"""""""""" Login required functions """""""""""""""""""

        """" Post Eval """
        try:
            context['my_post_eval'] = post.posteval_set.get(user=self.request.user)
        except PostEval.DoesNotExist:
            context['my_post_eval'] = post.posteval_set.create(user=self.request.user)

        return context


class PostCreateView(LoginRequiredMixin, generic.CreateView):
    """ Create view of posts """
    login_url = reverse_lazy('login')
    model = Post
    form_class = PostForm
    template_name = 'blogs/post.html'
    success_url = reverse_lazy('blogs:index')

    def form_valid(self, form):
        form.instance.create(self.request.user)
        messages.success(self.request, 'saved successfully!')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, 'not saved - alert!')
        return super().form_invalid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    """ Update view of posts """
    login_url = reverse_lazy('accounts:login')
    model = Post
    form_class = PostForm
    template_name = 'blogs/edit.html'

    def test_func(self):
        current_user = self.request.user
        post = get_object_or_404(self.model, pk=self.kwargs['pk'])
        author = post.author
        return current_user.pk == author.pk or current_user.is_superuser

    def get_success_url(self):
        """ If user can update the post, they are redirected to here """
        return reverse_lazy('blogs:detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        form.instance.publish()
        messages.success(self.request, 'saved successfully!')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, 'not saved - alert!')
        return super().form_invalid(form)


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    """ Delete view of posts """
    login_url = reverse_lazy('accounts:login')
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('blogs:index')

    def test_func(self):
        current_user = self.request.user
        post = get_object_or_404(self.model, pk=self.kwargs['pk'])
        author = post.author
        return current_user.pk == author.pk or current_user.is_superuser

    def delete(self, request, *args, **kwargs):
        result = super().delete(request, *args, **kwargs)
        messages.success(self.request, '"{}" was deleted.'.format(self.object))
        return result


class UserPageView(generic.TemplateView):
    """ User page view """
    template_name = 'blogs/user_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['dest_user'] = get_object_or_404(User, pk=self.kwargs['pk'])
        return context


class UserPostListView(generic.ListView):
    """ List view of the posts published by the user """
    template_name = 'blogs/user_posts.html'
    context_object_name = 'my_post_list'
    paginate_by = 15

    def get_queryset(self):
        queryset = Post.objects.filter(
            published_date__lte=timezone.now(),
            author=self.kwargs['pk'],
        ).order_by('-published_date')
        if not queryset:
            messages.info(self.request, 'No post exist')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['dest_user'] = get_object_or_404(User, pk=self.kwargs['pk'])
        return context


class UserProfileView(generic.TemplateView):
    """ User profile view """
    template_name = 'blogs/user_profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['dest_user'] = get_object_or_404(User, pk=self.kwargs['pk'])
        return context

blogs/templates/blogs/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en-us">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} Document {% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'blogs/css/css/bootstrap.min.css' %}">
    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'blogs/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/style.css' %}">
    <!-- jQuery -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="{% static 'blogs/js/js/jquery.bottom-1.0.js' %}"></script>

    <!-- Auth Exception -->
    {% if not user.is_authenticated %}
    <script>
        $(function(){
            $('.require-login').attr("data-toggle", "tooltip");
            $('.require-login').attr("title", "Need to log in");
            $('[data-toggle="tooltip"]').tooltip();
        })
    </script>
    {% endif %}

</head>

<body id="wrapper">

    <!-- navigator -->
    <nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark">
        <!-- <header> -->
        <a href="{% url 'blogs:index' %}" class="navbar-brand">TOP</a>

        <ul class="nav navbar-nav" id="navbar-search">
            <li class="nav-item active">
                {% include 'blogs/search_form.html' %}
            </li>
        </ul>

        <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNav4" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>



        <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">

            <!-- <ul class="nav navbar-nav mr-auto">
                <li class="nav-item active"><a href="#" class="nav-link active">Help</a></li>
            </ul> -->

            {% if user.is_authenticated %}
            <ul class="nav navbar-nav">

                <li class="nav-item active"><a class="nav-link active" href="{% url 'blogs:post' %}">New Post</a></li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'blogs:user_page' user.pk %}">My page</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'accounts:profile_settings' user.pk %}">Profile</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'accounts:settings' user.pk %}">Settings</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout </a>
                    </div>
                </li>
            </ul>
            {% else %}
            <ul class="nav navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link active" href="{% url 'accounts:login' %}">Sign in</a>
                </li>

                <li class="nav-item active">
                    <a class="nav-link active" href="{% url 'accounts:signup' %}">Sign Up</a>
                </li>
            </ul>
            {% endif %}

        </div>
        <!-- </header> -->
    </nav>


    <!-- main content -->
    <div id="main">
        {% block content %}{% endblock %}
    </div>

    <!-- sidebar -->
    <div id="sidebar">
        {% block sidebar %}{% endblock %}
    </div>

    <!-- footer -->
    <!-- <div id="footer">
        <footer class="footer mt-auto py-3">
            {%block footer%}
            <div class="container">
                <span class="text-muted">Footer</span>
            </div>
            {% endblock %}
        </footer>
    </div> -->

    <!-- message framework -->
    <div id="messages-container" class="fixed-bottom">
        {% if messages %}
        <ul class="messagelist">
            {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }} alert-dismissible alert-message" {% endif %} role="alert">
                <strong>{{ message }}</strong>
            </li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>

    <!-- bottom scroll -->
    <script src="{% static 'blogs/js/scroll.js' %}"></script>

    <script src="{% static 'blogs/js/message.js' %}"></script>

    <!-- Bootstrap4 -->
    <script src="{% static 'blogs/js/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Font Awesome -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>

</body>

</html>

blogs/templates/blogs/base_user_page.html
{% extends 'blogs/base.html' %}

{% block content %}

<div class="container my-5">
    <div id="userpage-header">
        <div id="head-container" class="">
            <div class="" id="user-container">
                <div class="col-2">

                </div>
                <div class="" id="user-icon">
                    <img src="{{ dest_user.icon_image.url }}" id="user-icon-image">
                </div>
                <div class="" id="user-name">
                    <span>{{ dest_user.username }}</span>
                </div>
            </div>
        </div>
        <div id="tabs-container" class="row no-gutters">
            <div class="tab-item col-2" id="tab-mypage">
                {% url 'blogs:user_page' dest_user.pk as user_page_url %}
                {% if request.path_info == user_page_url %}
                <a class="disabled">
                    <div class="background" id="tab-current">Home</div>
                </a>
                {% else %}
                <a href="{{ user_page_url }}" class="tab-link text-muted">
                    <div class="background">Home</div>
                </a>
                {% endif %}
            </div>
            <div class="tab-item col-2" id="tab-myposts">
                {% url 'blogs:user_posts' dest_user.pk as user_posts_url %}
                {% if request.path_info == user_posts_url %}
                <a class="disabled">
                    <div class="background" id="tab-current">Posts</div>
                </a>
                {% else %}
                <a href="{{ user_posts_url }}" class="tab-link text-muted">
                    <div class="background">Posts</div>
                </a>
                {% endif %}
            </div>
            <div class="tab-item col-2" id="tab-settings">
                {% url 'blogs:user_profile' dest_user.pk as profile_url %}
                {% if request.path_info == profile_url %}
                <a class="disabled">
                    <div class="background" id="tab-current">Profile</div>
                </a>
                {% else %}
                <a href="{{ profile_url }}" class="tab-link text-muted">
                    <div class="background">Profile</div>
                </a>
                {% endif %}
            </div>
        </div>
    </div>

    <div id="userpage-main-content">
        {% block main_content %}
        {% endblock %}
    </div>

</div>
<script>
    $(function () {
        $(".tab-link").hover(function () {
            $(this).removeClass("text-muted");
        }, function () {
            $(this).addClass("text-muted");
        })
    });
</script>
{% endblock %}

blogs/templates/blogs/detail.html
{% extends 'blogs/base.html' %}
{% load static %}
{% block content %}
<!-- <h1>Here is ID {{ post.pk }} detail</h1> -->


<div class="container my-5" id="post-container">
    <div class="row justify-content-center">
        <!-- Post author information -->
        <div class="col-9 my-3">
            <label hidden>Author:</label>
            <div id="author-container">
                <a href="{% url 'blogs:user_page' post.author.pk %}">
                    <div id="author-icon">
                        <img src="{{ post.author.icon_image.url }}" id="author-icon-image">
                    </div>
                </a>
                <div id="author-name">
                    <a href="{% url 'blogs:user_page' post.author.pk %}">{{ post.author.username }}</a>
                </div>
            </div>
        </div>
        
        {% if post.author.pk == request.user.pk or request.user.is_superuser %}
        <div class="col-9 my-3">
            <div class="row float-right">
                <!-- Edit URL -->
                <div class="col-5">
                    <a href="{% url 'blogs:edit' post.pk %}">
                        <button class="btn border" style="white-space: nowrap;">Edit   <i class="far fa-edit"></i></button>
                    </a>
                </div>
                <!-- Delete URL -->
                <div class="col-5">
                    <a href="{% url 'blogs:delete' post.pk %}">
                        <button class="btn border" style="white-space: nowrap;">Delete   <i class="far fa-trash-alt"></i></button>
                    </a>
                </div>
            </div>
        </div>
        {% endif %}

        <!-- Post updated date -->
        <div class="col-9">
            <div style="float:right">
                <label class="text-muted">Updated:</label>
                {{ post.published_date | date:'Y/m/d' }}
            </div>
        </div>
        <!-- Post media -->
        {% if post.image %}
        <div class="col-9 my-3">
            <label hidden>Image:</label>
            <a href="{{ post.image.url }}" target="blank"><img class="img-responsive mw-100" src="{{ post.image.url }}"></a>
        </div>
        {% endif %}


        <!-- Post title -->
        <div class="col-9 my-2">
            <div id="post-title">
                {{ post.title }}
            </div>
        </div>

        <!-- Post hit -->
        <div class="col-7 mb-2 clearfix" id="hit">
            <div class="float-right">
                <label class="text-muted">Views:</label>
                <span id="hit-count">{{ post_hit }}</span>
            </div>
        </div>

        <!-- Post Eval -->
        <div class="col-2 mb-2" id="post_eval">
            <div id="posteval-container" class="row float-right">
                <div class="posteval col" id="good-container">
                    <button class="btn require-login" id="good-button"><div class="icon"><i class="far fa-thumbs-up"></i></div></button>
                    <div id="good-count" class="text-center">{{ post_eval_good }}</div>
                </div>
                <div class="posteval col" id="bad-container">
                    <button class="btn require-login" id="bad-button"><div class="icon"><i class="far fa-thumbs-down"></i></div></button>
                    <div id="bad-count" class="text-center">{{ post_eval_bad }}</div>
                </div>
            </div>
        </div>


        <div class="border col-9"></div>
        <!-- PostText -->
        <div class="col-9 my-2">
            <div id="post-text">
                {{ post.text | linebreaksbr|urlize }}
            </div>
        </div>
    </div>
</div>

<!-- Comment -->
<div id="comment-container" class="container">
{% include 'blogs/comment.html' %}
</div>

{% csrf_token %}

<script>
    // postHit
    // Need csrf_token 

    $(function(){
        var hit = '{{ post_hit }}'
        $('#hit-count').html(hit);

        // POST method
        var $crf_token = $('[name="csrfmiddlewaretoken"]').attr('value');

        setTimeout(() => {
            $.ajax({
                url: '{% url "apis:posthit-list" %}',
                method: 'POST',
                data: {
                    'post': '{{ post.pk }}',
                    'user': '{{ user.pk }}',
                    'hit': true
                },
                headers: { "X-CSRFToken": $crf_token }, // csrf_token
            })
                .fail((response) => {
                    console.log('PostHit POST fail!');
                })
        }, 10000) // 10 sec
    })
</script>

{% if user.is_authenticated %}
<script>
    // postEval
    // Need csrf_token

    $(function () {
        var good_button = $('#good-button');
        var bad_button = $('#bad-button');
        var good_field = $('#good-count');
        var bad_field = $('#bad-count');
        var good_count = Number('{{ post_eval_good }}');
        var bad_count = Number('{{ post_eval_bad }}');

        const good_selected = 'btn-primary';
        const bad_selected = 'btn-danger';

        if ('{{ my_post_eval.good }}' == 'True') {
            good_button.addClass(good_selected);
        }

        if ('{{ my_post_eval.bad }}' == 'True') {
            bad_button.addClass(bad_selected);
        }

        // PUT Method
        var $crf_token = $('[name="csrfmiddlewaretoken"]').attr('value');

        good_button.on('click', function () {
            if ($(this).hasClass(good_selected)) {
                putPostEval(false, false);
                good_field.html(--good_count);
                $(this).removeClass(good_selected);
            } else {
                putPostEval(true, false);
                if (bad_button.hasClass(bad_selected)) {
                    bad_field.html(--bad_count);
                    bad_button.removeClass(bad_selected);
                }
                good_field.html(++good_count);
                $(this).addClass(good_selected);
            }
        });

        bad_button.on('click', function () {
            if ($(this).hasClass(bad_selected)) {
                putPostEval(false, false);
                bad_field.html(--bad_count);
                $(this).removeClass(bad_selected);
            } else {
                putPostEval(false, true);
                if (good_button.hasClass(good_selected)) {
                    good_field.html(--good_count);
                    good_button.removeClass((good_selected));
                }
                bad_field.html(++bad_count);
                $(this).addClass(bad_selected);
            }
        });

        var putPostEval = function (good, bad) {
            $.ajax({
                url: '{% url "apis:posteval-detail" my_post_eval.pk %}',
                method: 'PUT',
                data: {
                    'post': '{{ post.pk }}',
                    'user': '{{ user.pk }}',
                    'good': good,
                    'bad': bad,
                },
                headers: { 'X-CSRFToken': $crf_token }, // csrf_token
            })
                .fail((response) => {
                    console.log('PUT fail!');
                })
        }
    })
</script>
{% endif %}

{% endblock %}